[package]
name = "attr-wrapper"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.79", features = ["full"] }
quote = "1.0.37"

[dev-dependencies]
log = "0.4.25"